### PR TITLE
Use DHT22 to parameterize MQ135 and send to IOT HUB

### PR DESCRIPTION
**Pull request by SanderGi**
The ESP8266 microcontroller reads temperature and humidity from the DHT22 chip; passes the information to the MQ135 gas sensor so it can find the concentration of NH3, NOx, alcohol, Benzene, smoke, CO2, etc. in PPM; and finally prints it all to the serial monitor.

Here’s the information logged on startup:
image

And the information printed in a loop:
image

### CODE REVIEW

**Comment by SanderGi** [comment]
This uses [Platform IO via VS Code](https://docs.platformio.org/en/latest/integration/ide/vscode.html#quick-start). To run, follow the linked instructions for installing the Platform IO extension into VS Code, restart VS Code, clone this project, open it in Platform IO, and click upload in the toolbar, then select the serial monitor (also in the toolbar) to see the output.

**Comment by SanderGi** [comment]
It is also necessary to add the following dependencies, however if you initialize the project via Platform IO, as explained above, this will be done automatically.
image

**Comment by SanderGi** [comment]
If you want, you can install the dependencies manually and link them when compiling main.cpp and Platform IO wont be necessary

**Comment by SanderGi** [comment]
The iot hub telemetry payload now includes sensor data:
```
{
    "event": {
        "origin": "alexDevice",
        "module": "",
        "interface": "",
        "component": "",
        "payload": "{ \"msgCount\": 1, \"temperature\": 26.90, \"humidity\": 56.60, \"rzero\": 11.04, \"correctedRZero\": 11.85, \"resistance\": 6.97, \"ppm\": 89240.96, \"correctedPPM\": 73346.52 }"
    }
}
```

**Review by grigoryshatalin — APPROVED** [review]
looks good

**Pull request merged**
